### PR TITLE
adds .bat support

### LINKED ISSUE #1: Add .bat support
This package was originally created only as .sh files.  It would be nice to add .bat support at some point.  Contributions welcome!

### PR DESCRIPTION
**Pull request by mfansler**
This adds **.bat** file (and **win-64**) support. Also, adding myself as a maintainer.

## Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

## Related Issues

Closes #1.

### CODE REVIEW

**Comment by mfansler** [comment]
@conda-forge-admin, please rerender

**Comment by mfansler** [comment]
@conda-forge/core ready for review 🙏

**Comment by fgp** [comment]
Thank you for the patch!

I noticed that the test cases for Windows only test the Python-specific variablw, not the R-specific one. Would it be possible for you to test the R-variable as well for consistency?

Otherwise, everything looks good as far as I can see. I don't have a Windows machine running Conda at hand to test, but since the tests pass, I'll assume that everything works correctly.

(In the original version oft his comment I had assumed that Windows code only handles Python, not R, but now realized that applies only to the test case, not the actual activation and deactivation code)

**Comment by mfansler** [comment]
@fgp thanks for reviewing! I've now added the `R_LIBS_USER` test for Windows.

**Pull request merged**
